spring:
  datasource:
    password: 980508    #数据库1
    username: root
    url: jdbc:mysql://121.89.167.102:3306/mimall?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 121.89.167.102
    port: 6379
    password: 980508
mybatis:
  configuration:
    map-underscore-to-camel-case: true    #驼峰命名法
    #控制台日志，输出sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml  #使用xml时导入mappers包