spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://192.168.206.131:3307/mimall?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true    #驼峰命名法
  mapper-locations: classpath:mappers/*.xml  #使用xml时导入mappers包